### ISSUE TITLE
App DB format

### ISSUE THREAD

**Issue by TheTechmage** [pebble-dev/rebblestore-api#1]
We need to figure out some form a schema to store app information in.

**Comment by HenryDelMal** [comment]
Apart of schema, we'll use sqlite before and then select other engine? In Discord was proposed postgres

**Comment by TheTechmage** [comment]
SQLite first is indeed the plan. So long as we stick with SQL syntax, we
should be able to easily switch libraries later due to Go's SQL library.

~ Sent from my Alphabet phone

**Comment by Klikini** [comment]
Here is a draft schema for PostgreSQL: https://gist.github.com/Klikini/2a95651082cfd282bfdd5984f7275a5b

**Edit 1:** I have removed the developers table because it was redundant. Any user can upload apps. A separate developer status flag can be added if needed in the future.

**Edit 2:** Oops, I totally forgot about platforms! Each version of an app can now specify a list of compatible platforms.

**Edit 3:** Added a field to apps to allow developers to opt-out of having their app included in store exports/archives.
